[package]
name = "kls_os"
version = "0.0.3-1"
edition = "2021"

[dependencies]
bootloader = "0.9.29"
spin = "0.9.8"
lazy_static = { version = "1.0", features = ["spin_no_std"] }
x86_64 = "0.14.12"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
